# Generated by Django 3.2.7 on 2021-09-06 22:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_conspiracy_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conspiracy',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 9, 6, 22, 9, 2, 468282, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='conspiracy',
            name='description',
            field=models.TextField(max_length=500000),
        ),
    ]
