# Generated by Django 3.2.7 on 2021-09-07 20:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210906_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='conspiracy',
            name='preview',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conspiracy',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 9, 7, 20, 46, 21, 677320, tzinfo=utc)),
        ),
    ]
