# Generated by Django 3.2.7 on 2021-09-07 21:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_conspiracy_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conspiracy',
            old_name='title1',
            new_name='preview',
        ),
        migrations.AlterField(
            model_name='conspiracy',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 9, 7, 21, 10, 32, 514962, tzinfo=utc)),
        ),
    ]
