# Generated by Django 3.2.7 on 2021-09-07 21:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20210907_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conspiracy',
            name='preview',
        ),
        migrations.AlterField(
            model_name='conspiracy',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 9, 7, 21, 11, 9, 426288, tzinfo=utc)),
        ),
    ]
