# Generated by Django 3.2.7 on 2021-09-07 21:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20210907_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='conspiracy',
            name='preview',
            field=models.CharField(default='Some String', max_length=50),
        ),
        migrations.AlterField(
            model_name='conspiracy',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 9, 7, 21, 21, 34, 766740, tzinfo=utc)),
        ),
    ]
